### ISSUE TITLE
Possibility to choose the algorithm

### ISSUE THREAD

**Issue by sitexw** [mozilla/srihash.org#123]
Hello, is it possible to add a "select" tag to be able to choose the algorithm?

**Comment by fmarier** [comment]
> Hello, is it possible to add a "select" tag to be able to choose the algorithm?

There is one already, but it's hidden. If you use the developer tools to change it to a `text` input type, then you can choose the hash algorithm you want (`sha256`, `sha384`, `sha512`) and submit the form.

We chose not to expose this to users though in order to keep the webapp as simple as possible and to steer people towards a safe default.

**Comment by sitexw** [comment]
Yes I know, but I would have found it more convenient and nice that we can select it directly. And to encourage safety, preselect default "sha384" or "SHA512".
