### ISSUE TITLE
Why SHA384?

### ISSUE THREAD

**Issue by rugk** [mozilla/srihash.org#155]
Why not other hashing algorithms? (SHA-256 or SHA-512) What is the rationale behind it?

Do not all browsers support SHA-512 or SHA-256 e.g.?

I am asking this also, because I have no idea about the browser support and some statistics would be helpful for https://github.com/PrivateBin/PrivateBin/issues/123.

**Comment by fmarier** [comment]
> Why not other hashing algorithms? (SHA-256 or SHA-512) What is the rationale behind it?

We only use a single algorithm because that's all you need (the browser only looks at the strongest one) and it makes the HTML shorter. As for why we chose SHA384, see https://github.com/w3c/webappsec/issues/477.

> Do not all browsers support SHA-512 or SHA-256 e.g.?

They all do, it's required by the spec. The support for multiple hashes is in the spec for backward-compatibility once we introduce new hash algorithms (e.g. SHA3).

I hope this helps.

**Comment by rugk** [comment]
Yes, this helps indeed.
