### ISSUE TITLE
SSL cert revoked error

### ISSUE THREAD

**Issue by XhmikosR** [mozilla/srihash.org#208]
I'm getting `An error occurred during a connection to srihash.org. Peer’s Certificate has been revoked. Error code: SEC_ERROR_REVOKED_CERTIFICATE `

/CC @fmarier

**Comment by fmarier** [comment]
I don't work at Mozilla anymore, but hopefully @mozfreddyb can ping the right person.

**Comment by mozfreddyb** [comment]
Looking (this will take a while)

**Comment by mozfreddyb** [comment]
@XhmikosR There's a redirect bug that will need a few hours to be fixed completely, due to DNS propagation.

https://www.srihash.org/ still works!

**Comment by XhmikosR** [comment]
We should really add the domain to https://hstspreload.org/?domain=srihash.org

IIRC I already made the change to send the proper HSTS header a long time ago. We just need to make sure SSL does not break again in the future.

**Comment by mozfreddyb** [comment]
It's actually using LetsEncrypt & ACME though Heroku. It's just that the apex domain has an incorrect DNS entry pointing to a Mozilla redirector that goes back to www.srihash.org. The redirection part goes through Mozilla infra, which does not have a correct certificate.
I've filed [bug 1530297](https://bugzilla.mozilla.org/show_bug.cgi?id=1530297), to get the DNS entries in order and make it independent of un-automated Mozilla infra. Once that has propagated through caches, we should be done.

Regarding HSTS: I have a long list of priorities in work and live and being the admin for this website is frankly at the very bottom of this list. My experience with ACME and cert-renewal on Heroku is zero. I'm not great at fixing those proprietary-infra fails on my own and do not want to increase pressure on my by making failures more dire, due to browsers refusing to load the page.

HSTS is nice, I agree. But in this case, I'd rather wait to ensure all things are running smoothly before committing to it.

**Comment by mozfreddyb** [comment]
actually, looking at your link...it seems www.srihash.org is already preloaded.
