### ISSUE TITLE
Hash for <link> tag

### ISSUE THREAD

**Issue by kota-yata** [mozilla/srihash.org#457]
When I hash css file or Google fonts, I got a script like so:
![image](https://user-images.githubusercontent.com/51294895/90979327-548f8f80-e58f-11ea-9430-f99e58680ce7.png)
I have to copy only ```integrity``` and ```crossorigin```, and this is not good.

I think I can avoid this by judging the file format from end of url, but in case of Google fonts, this way is not helpful.

Does anyone have a solution?

**Comment by mozfreddyb** [comment]
The `response` in https://github.com/mozilla/srihash.org/blob/gh-pages/app.js#L48, should allow you to inspect the headers, as `response.headers.get("content-type")` and then switch based on that.

To do so, the code needs to be cleaned up a bit.
I propose splitting up the following things into their own functions:
- `parseContentType` should take a content-type header and split on `;` (if available) and then match "text/css" into "style" and everything else into "script" (because a lot of websites still send various types like text/plain etc. for scripts).
- adding HTML to the resultDiv should also be its own function and called like so `displayResult(resultDiv, url, parsedContentType, text /* the file content */)`
- - `displayResult` needs to generate the HTML and append it via innerHTML.
- - generating `integrityMetadata` should be its own function, it should return a `sha384-xyz` string and be called from within `displayResult`.
- - Escaping should happen inside the function `displayResult`.

Makes sense?

**Comment by kota-yata** [comment]
Thanks, I almost get it.

**Comment by kota-yata** [comment]
Should I separate js file like ```contentType.js```?
If I separate, I need to disable some eslint rules.

**Comment by mozfreddyb** [comment]
I don't think it needs to be separated
