### ISSUE TITLE
Check for the presence of CORS headers

### ISSUE THREAD

**Issue by fmarier** [mozilla/srihash.org#61]
Now that CORS is required for cross-origin requests, we should issue a warning when it's not there.

It shouldn't be an error because maybe the author will be loading that resource over the same origin, even though that's less likely.

There are three possibilities:

1. `Access-Control-Allow-Origin: *`: open to everyone, no warning.
2. `Access-Control-Allow-Origin: example.com`: only works if loaded from `example.com` or `example.net`, we should include those in the warning (after sanitizing them of course)
3. No `Access-Control-Allow-Origin` header: warning that CORS is required for cross-origin loads

I can't find good examples for the second one though, so maybe we should tackle 1 and 3 for now.

**Comment by neftaly** [comment]
The client-side lookups will adhere to CORS (by design), so they'll fail if `srihash.org` is not a permitted endpoint. I'm actually working on it right now (funny that you started pushing these changes now, I literally started work ~5-10 minutes beforehand). We can discuss a server-side fallback for failed client-side cross-origin requests when I make the appropriate PR.

**Comment by fmarier** [comment]
> funny that you started pushing these changes now, I literally started work ~5-10 minutes beforehand

I'm giving [a talk](https://conference.auscert.org.au/francois-marier) on SRI next week so I want to fix the most embarrassing bugs before then :)
